from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import QRect, Qt, QSize
from PySide6.QtGui import QPixmap, QFont, QIcon, QBrush, QColor
from PySide6.QtWidgets import QLabel, QGroupBox, QHBoxLayout, QVBoxLayout, QListWidgetItem
from qfluentwidgets import PushButton, LineEdit, ListWidget

from tools.clicked_tabel import MyQLabel


class Set_question:
    def set_return(self, ico, text, dir):  # 头像，文本，方向0
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setLayoutDirection(dir)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(45, 45))
        self.label.setText("")
        self.label.setPixmap(ico)
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("padding:8px;\n"
                                       "background-color: #c7e3fc;\n"
                                       "font: 13pt \"Zpix\";\n"
                                       "border-radius:15px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setText(text)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.widget)

    def set_return_png(self, ico, png, dir, user_or_bot):  # 头像，图片，方向
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setLayoutDirection(dir)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        if user_or_bot == 'bot':
            self.label = QtWidgets.QLabel(self.widget)
            self.label.setMaximumSize(QtCore.QSize(45, 45))
            self.label.setMinimumSize(QtCore.QSize(0, 0))
            self.label.setText("")
            self.label.setPixmap(ico)
            self.label.setScaledContents(True)
            self.label.setObjectName("label")
            self.horizontalLayout.addWidget(self.label)
        else:
            pass
        # 图片消息
        self.label2 = QLabel(self.widget)
        self.label2.setObjectName(u"label2")
        self.label2.setPixmap(QPixmap(png))
        self.label2.setScaledContents(False)

        self.horizontalLayout.addWidget(self.label2)
        self.verticalLayout.addWidget(self.widget)

    def return_emoji_line(self):
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_love = MyQLabel(self)
        self.label_love.setObjectName(u"label_love")
        self.label_love.setPixmap(QPixmap(u"file/emoji/love.png"))
        # 设置这个label的背景颜色为：background-color: rgb(213, 183, 222);

        self.horizontalLayout_5.addWidget(self.label_love, 0, Qt.AlignHCenter)

        self.label_idc = MyQLabel(self)
        self.label_idc.setObjectName(u"label_idc")
        self.label_idc.setPixmap(QPixmap(u"file/emoji/idc.png"))

        self.horizontalLayout_5.addWidget(self.label_idc, 0, Qt.AlignHCenter)

        self.label_ok = MyQLabel(self)
        self.label_ok.setObjectName(u"label_ok")
        self.label_ok.setPixmap(QPixmap(u"file/emoji/ok.png"))

        self.horizontalLayout_5.addWidget(self.label_ok, 0, Qt.AlignHCenter)

        self.label_die = MyQLabel(self)
        self.label_die.setObjectName(u"label_die")
        self.label_die.setTextFormat(Qt.AutoText)
        self.label_die.setPixmap(QPixmap(u"file/emoji/die.png"))
        self.label_die.setScaledContents(False)

        self.horizontalLayout_5.addWidget(self.label_die, 0, Qt.AlignHCenter)

        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_omg = MyQLabel(self)
        self.label_omg.setObjectName(u"label_omg")
        self.label_omg.setPixmap(QPixmap(u"file/emoji/omg.png"))

        self.horizontalLayout_4.addWidget(self.label_omg, 0, Qt.AlignHCenter)

        self.label_sorry = MyQLabel(self)
        self.label_sorry.setObjectName(u"label_sorry")
        self.label_sorry.setPixmap(QPixmap(u"file/emoji/sorry.png"))

        self.horizontalLayout_4.addWidget(self.label_sorry, 0, Qt.AlignHCenter)

        self.label_this = MyQLabel(self)
        self.label_this.setObjectName(u"label_this")
        self.label_this.setPixmap(QPixmap(u"file/emoji/this.png"))

        self.horizontalLayout_4.addWidget(self.label_this, 0, Qt.AlignHCenter)

        self.label_cry = MyQLabel(self)
        self.label_cry.setObjectName(u"label_cry")
        self.label_cry.setPixmap(QPixmap(u"file/emoji/cry.png"))

        self.horizontalLayout_4.addWidget(self.label_cry, 0, Qt.AlignHCenter)

        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.LineEdit_emoji = LineEdit(self)

        self.LineEdit_emoji.setObjectName(u"LineEdit_emoji")
        self.LineEdit_emoji.setStyleSheet(u"LineEdit, TextEdit, PlainTextEdit {\n"
                                          "\n"
                                          "    background-color:#f8e2fd;\n"
                                          "    border: 1px solid rgba(0, 0, 0, 13);\n"
                                          "    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
                                          "    border-radius: 15px;\n"
                                          "    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
                                          "	font: 500 11pt \"Zpix\";\n"
                                          "    padding: 0px 10px;\n"
                                          "    selection-background-color: #00a7b3;\n"
                                          "}\n"
                                          "\n"
                                          "TextEdit,\n"
                                          "PlainTextEdit {\n"
                                          "    padding: 2px 3px 2px 8px;\n"
                                          "}\n"
                                          "\n"
                                          "LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
                                          "    background-color: #f8e2fd;\n"
                                          "    border: 1px solid rgba(0, 0, 0, 13);\n"
                                          "    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
                                          "}\n"
                                          "\n"
                                          "TextEdit:focus,\n"
                                          "PlainTextEdit:focus {\n"
                                          "    border-bottom: 1px solid #009faa;\n"
                                          "    background-color: #f8e2fd;\n"
                                          "}\n"
                                          "\n"
                                          "LineEdit:disabled, TextEdit:disabled,\n"
                                          "PlainTextEdit:disabled {\n"
                                          "    color: rgba(0, 0, 0, 150);\n"
                                          "    background-color: rgba(249, 249, 249, 0.3);\n"
                                          "    border: 1px solid rgba(0, 0, 0, 13);\n"
                                          "    border-bottom: 1px solid"
                                          " rgba(0, 0, 0, 13);\n"
                                          "}\n"
                                          "\n"
                                          "#lineEditButton {\n"
                                          "    background-color: transparent;\n"
                                          "    border-radius: 4px;\n"
                                          "    margin: 0;\n"
                                          "}\n"
                                          "\n"
                                          "#lineEditButton:hover {\n"
                                          "    background-color: rgba(0, 0, 0, 9);\n"
                                          "}\n"
                                          "\n"
                                          "#lineEditButton:pressed {\n"
                                          "    background-color: rgba(0, 0, 0, 6);\n"
                                          "}\n"
                                          "")

        self.horizontalLayout.addWidget(self.LineEdit_emoji)

        self.PushButton_emoji = PushButton(self)
        self.PushButton_emoji.setObjectName(u"PushButton_emoji")
        self.PushButton_emoji.setStyleSheet(u"PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
                                            "    color: black;\n"
                                            "    background: rgba(255, 255, 255, 0.7);\n"
                                            "    border: 1px solid rgba(0, 0, 0, 0.073);\n"
                                            "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                            "    border-radius: 8px;\n"
                                            "    /* font: 14px 'Segoe UI', 'Microsoft YaHei'; */\n"
                                            "    padding: 5px 12px 6px 12px;\n"
                                            "    outline: none;\n"
                                            "}\n"
                                            "\n"
                                            "ToolButton {\n"
                                            "    padding: 5px 9px 6px 8px;\n"
                                            "}\n"
                                            "\n"
                                            "PushButton[hasIcon=false] {\n"
                                            "    padding: 5px 12px 6px 12px;\n"
                                            "}\n"
                                            "\n"
                                            "PushButton[hasIcon=true] {\n"
                                            "    padding: 5px 12px 6px 36px;\n"
                                            "}\n"
                                            "\n"
                                            "DropDownToolButton, PrimaryDropDownToolButton {\n"
                                            "    padding: 5px 31px 6px 8px;\n"
                                            "}\n"
                                            "\n"
                                            "DropDownPushButton[hasIcon=false],\n"
                                            "PrimaryDropDownPushButton[hasIcon=false] {\n"
                                            "    padding: 5px 31px 6px 12px;\n"
                                            "}\n"
                                            "\n"
                                            "DropDownPushButton[hasIcon=true],\n"
                                            "PrimaryDropDownPushButton[hasIcon=true] {\n"
                                            "    padding: 5px 31px 6px 36px;\n"
                                            "}\n"
                                            "\n"
                                            "PushButton:hover, ToolButton:hover, ToggleButton:hover, To"
                                            "ggleToolButton:hover {\n"
                                            "    background: rgba(249, 249, 249, 0.5);\n"
                                            "}\n"
                                            "\n"
                                            "PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
                                            "    color: rgba(0, 0, 0, 0.63);\n"
                                            "    background: rgba(249, 249, 249, 0.3);\n"
                                            "    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
                                            "}\n"
                                            "\n"
                                            "PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
                                            "    color: rgba(0, 0, 0, 0.36);\n"
                                            "    background: rgba(249, 249, 249, 0.3);\n"
                                            "    border: 1px solid rgba(0, 0, 0, 0.06);\n"
                                            "    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "PrimaryPushButton,\n"
                                            "PrimaryToolButton,\n"
                                            "ToggleButton:checked,\n"
                                            "ToggleToolButton:checked {\n"
                                            "    color: white;\n"
                                            "    background-color: #009faa;\n"
                                            "    border: 1px solid #00a7b3;\n"
                                            "    border-bottom: 1px solid #007780;\n"
                                            "}\n"
                                            "\n"
                                            "PrimaryPushButton:hover,\n"
                                            "PrimaryToolButton:hover,\n"
                                            "ToggleButton:checked:hover,\n"
                                            "ToggleToolButton:checked:hover {\n"
                                            "    background-color: #00a7b3"
                                            ";\n"
                                            "    border: 1px solid #2daab3;\n"
                                            "    border-bottom: 1px solid #007780;\n"
                                            "}\n"
                                            "\n"
                                            "PrimaryPushButton:pressed,\n"
                                            "PrimaryToolButton:pressed,\n"
                                            "ToggleButton:checked:pressed,\n"
                                            "ToggleToolButton:checked:pressed {\n"
                                            "    color: rgba(255, 255, 255, 0.63);\n"
                                            "    background-color: #3eabb3;\n"
                                            "    border: 1px solid #3eabb3;\n"
                                            "}\n"
                                            "\n"
                                            "PrimaryPushButton:disabled,\n"
                                            "PrimaryToolButton:disabled,\n"
                                            "ToggleButton:checked:disabled,\n"
                                            "ToggleToolButton:checked:disabled {\n"
                                            "    color: rgba(255, 255, 255, 0.9);\n"
                                            "    background-color: rgb(205, 205, 205);\n"
                                            "    border: 1px solid rgb(205, 205, 205);\n"
                                            "}\n"
                                            "\n"
                                            "SplitDropButton,\n"
                                            "PrimarySplitDropButton {\n"
                                            "    border-left: none;\n"
                                            "    border-top-left-radius: 0;\n"
                                            "    border-bottom-left-radius: 0;\n"
                                            "}\n"
                                            "\n"
                                            "#splitPushButton,\n"
                                            "#splitToolButton,\n"
                                            "#primarySplitPushButton,\n"
                                            "#primarySplitToolButton {\n"
                                            "    border-top-right-radius: 0;\n"
                                            "    border-bottom-right-radius: 0;\n"
                                            "}\n"
                                            "\n"
                                            "#splitPushButton:pressed,\n"
                                            "#splitTool"
                                            "Button:pressed,\n"
                                            "SplitDropButton:pressed {\n"
                                            "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                            "}\n"
                                            "\n"
                                            "PrimarySplitDropButton:pressed {\n"
                                            "    border-bottom: 1px solid #007780;\n"
                                            "}\n"
                                            "\n"
                                            "#primarySplitPushButton, #primarySplitToolButton {\n"
                                            "    border-right: 1px solid #3eabb3;\n"
                                            "}\n"
                                            "\n"
                                            "#primarySplitPushButton:pressed, #primarySplitToolButton:pressed {\n"
                                            "    border-bottom: 1px solid #007780;\n"
                                            "}\n"
                                            "\n"
                                            "HyperlinkButton {\n"
                                            "    /* font: 14px 'Segoe UI', 'Microsoft YaHei'; */\n"
                                            "    padding: 6px 12px 6px 12px;\n"
                                            "    color: #009faa;\n"
                                            "    border: none;\n"
                                            "    border-radius: 6px;\n"
                                            "    background-color: transparent;\n"
                                            "}\n"
                                            "\n"
                                            "HyperlinkButton[hasIcon=false] {\n"
                                            "    padding: 6px 12px 6px 12px;\n"
                                            "}\n"
                                            "\n"
                                            "HyperlinkButton[hasIcon=true] {\n"
                                            "    padding: 6px 12px 6px 36px;\n"
                                            "}\n"
                                            "\n"
                                            "HyperlinkButton:hover {\n"
                                            "    color: #009faa;\n"
                                            "    background-color: rgba(0, 0, 0, 10);\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "\n"
                                            "HyperlinkButton:pressed {\n"
                                            "    color: #009faa;\n"
                                            ""
                                            "    background-color: rgba(0, 0, 0, 6);\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "\n"
                                            "HyperlinkButton:disabled {\n"
                                            "    color: rgba(0, 0, 0, 0.43);\n"
                                            "    background-color: transparent;\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "RadioButton {\n"
                                            "    min-height: 24px;\n"
                                            "    max-height: 24px;\n"
                                            "    background-color: transparent;\n"
                                            "    font: 14px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';\n"
                                            "    color: black;\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator {\n"
                                            "    width: 18px;\n"
                                            "    height: 18px;\n"
                                            "    border-radius: 11px;\n"
                                            "    border: 2px solid #999999;\n"
                                            "    background-color: rgba(0, 0, 0, 5);\n"
                                            "    margin-right: 4px;\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:hover {\n"
                                            "    background-color: rgba(0, 0, 0, 0);\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:pressed {\n"
                                            "    border: 2px solid #bbbbbb;\n"
                                            "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                            "            stop:0 rgb(255, 255, 255),\n"
                                            "            stop:0.5 rgb(255, 255, 255),\n"
                                            "            stop:0.6 rgb(225, 2"
                                            "24, 223),\n"
                                            "            stop:1 rgb(225, 224, 223));\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:checked {\n"
                                            "    height: 22px;\n"
                                            "    width: 22px;\n"
                                            "    border: none;\n"
                                            "    border-radius: 11px;\n"
                                            "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                            "            stop:0 rgb(255, 255, 255),\n"
                                            "            stop:0.5 rgb(255, 255, 255),\n"
                                            "            stop:0.6 #009faa,\n"
                                            "            stop:1 #009faa);\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:checked:hover {\n"
                                            "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                            "            stop:0 rgb(255, 255, 255),\n"
                                            "            stop:0.6 rgb(255, 255, 255),\n"
                                            "            stop:0.7 #009faa,\n"
                                            "            stop:1 #009faa);\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:checked:pressed {\n"
                                            "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                            "            stop:0 rgb(255, 255, 255),\n"
                                            "            stop:0.5 rgb(255, 255, 255),\n"
                                            "            stop:0.6 #0"
                                            "09faa,\n"
                                            "            stop:1 #009faa);\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton:disabled {\n"
                                            "    color: rgba(0, 0, 0, 110);\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:disabled {\n"
                                            "    border: 2px solid #bbbbbb;\n"
                                            "    background-color: transparent;\n"
                                            "}\n"
                                            "\n"
                                            "RadioButton::indicator:disabled:checked {\n"
                                            "    border: none;\n"
                                            "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                            "            stop:0 rgb(255, 255, 255),\n"
                                            "            stop:0.5 rgb(255, 255, 255),\n"
                                            "            stop:0.6 rgba(0, 0, 0, 0.2169),\n"
                                            "            stop:1 rgba(0, 0, 0, 0.2169));\n"
                                            "}\n"
                                            "\n"
                                            "TransparentToolButton,\n"
                                            "TransparentToggleToolButton,\n"
                                            "TransparentDropDownToolButton,\n"
                                            "TransparentPushButton,\n"
                                            "TransparentDropDownPushButton,\n"
                                            "TransparentTogglePushButton {\n"
                                            "    background-color: transparent;\n"
                                            "    border: none;\n"
                                            "    border-radius: 5px;\n"
                                            "    margin: 0;\n"
                                            "}\n"
                                            "\n"
                                            "TransparentToolButton:hover,\n"
                                            "TransparentToggleToolButton:hover,\n"
                                            "TransparentDropDownToolButton:ho"
                                            "ver,\n"
                                            "TransparentPushButton:hover,\n"
                                            "TransparentDropDownPushButton:hover,\n"
                                            "TransparentTogglePushButton:hover {\n"
                                            "    background-color: rgba(0, 0, 0, 9);\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "\n"
                                            "TransparentToolButton:pressed,\n"
                                            "TransparentToggleToolButton:pressed,\n"
                                            "TransparentDropDownToolButton:pressed,\n"
                                            "TransparentPushButton:pressed,\n"
                                            "TransparentDropDownPushButton:pressed,\n"
                                            "TransparentTogglePushButton:pressed {\n"
                                            "    background-color: rgba(0, 0, 0, 6);\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "\n"
                                            "TransparentToolButton:disabled,\n"
                                            "TransparentToggleToolButton:disabled,\n"
                                            "TransparentDropDownToolButton:disabled,\n"
                                            "TransprentPushButton:disabled,\n"
                                            "TransparentDropDownPushButton:disabled,\n"
                                            "TransprentTogglePushButton:disabled {\n"
                                            "    background-color: transparent;\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "PillPushButton,\n"
                                            "PillPushButton:hover,\n"
                                            "PillPushButton:pressed,\n"
                                            "PillPushButton:disabled,\n"
                                            "PillPushButton:checked,\n"
                                            "PillPushButton:checked:hover,\n"
                                            "PillPushButton:checked:p"
                                            "ressed,\n"
                                            "PillPushButton:disabled:checked,\n"
                                            "PillToolButton,\n"
                                            "PillToolButton:hover,\n"
                                            "PillToolButton:pressed,\n"
                                            "PillToolButton:disabled,\n"
                                            "PillToolButton:checked,\n"
                                            "PillToolButton:checked:hover,\n"
                                            "PillToolButton:checked:pressed,\n"
                                            "PillToolButton:disabled:checked {\n"
                                            "    background-color: transparent;\n"
                                            "    border: none;\n"
                                            "}\n"
                                            "")
        icon = QIcon()
        icon.addFile(u"file/background/9165747_send_mail_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.PushButton_emoji.setIcon(icon)

        self.horizontalLayout.addWidget(self.PushButton_emoji)
        # 输入框与按钮
        self.horizontalLayout.setStretch(0, 8)

        self.verticalLayout.addLayout(self.horizontalLayout)

        self.PushButton_emoji.setText("Send")

    def return_choose_list(self):
        self.ListWidget_choose = ListWidget(self)
        self.ListWidget_choose.setObjectName(u"ListWidget")

        self.verticalLayout.addWidget(self.ListWidget_choose)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.LineEdit_choose = LineEdit(self)
        self.LineEdit_choose.setObjectName(u"LineEdit_choose")
        self.LineEdit_choose.setStyleSheet(u"LineEdit, TextEdit, PlainTextEdit {\n"
                                           "\n"
                                           "    background-color:#f8e2fd;\n"
                                           "    border: 1px solid rgba(0, 0, 0, 13);\n"
                                           "    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
                                           "    border-radius: 15px;\n"
                                           "    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
                                           "	font: 500 11pt \"Zpix\";\n"
                                           "    padding: 0px 10px;\n"
                                           "    selection-background-color: #00a7b3;\n"
                                           "}\n"
                                           "\n"
                                           "TextEdit,\n"
                                           "PlainTextEdit {\n"
                                           "    padding: 2px 3px 2px 8px;\n"
                                           "}\n"
                                           "\n"
                                           "LineEdit:hover, TextEdit:hover, PlainTextEdit:hover {\n"
                                           "    background-color: #f8e2fd;\n"
                                           "    border: 1px solid rgba(0, 0, 0, 13);\n"
                                           "    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
                                           "}\n"
                                           "\n"
                                           "TextEdit:focus,\n"
                                           "PlainTextEdit:focus {\n"
                                           "    border-bottom: 1px solid #009faa;\n"
                                           "    background-color: #f8e2fd;\n"
                                           "}\n"
                                           "\n"
                                           "LineEdit:disabled, TextEdit:disabled,\n"
                                           "PlainTextEdit:disabled {\n"
                                           "    color: rgba(0, 0, 0, 150);\n"
                                           "    background-color: rgba(249, 249, 249, 0.3);\n"
                                           "    border: 1px solid rgba(0, 0, 0, 13);\n"
                                           "    border-bottom: 1px solid"
                                           " rgba(0, 0, 0, 13);\n"
                                           "}\n"
                                           "\n"
                                           "#lineEditButton {\n"
                                           "    background-color: transparent;\n"
                                           "    border-radius: 4px;\n"
                                           "    margin: 0;\n"
                                           "}\n"
                                           "\n"
                                           "#lineEditButton:hover {\n"
                                           "    background-color: rgba(0, 0, 0, 9);\n"
                                           "}\n"
                                           "\n"
                                           "#lineEditButton:pressed {\n"
                                           "    background-color: rgba(0, 0, 0, 6);\n"
                                           "}\n"
                                           "")

        self.horizontalLayout.addWidget(self.LineEdit_choose)

        self.PushButton_choose = PushButton(self)
        self.PushButton_choose.setObjectName(u"PushButton_choose")
        self.PushButton_choose.setStyleSheet(u"PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
                                             "    color: black;\n"
                                             "    background: rgba(255, 255, 255, 0.7);\n"
                                             "    border: 1px solid rgba(0, 0, 0, 0.073);\n"
                                             "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                             "    border-radius: 8px;\n"
                                             "    /* font: 14px 'Segoe UI', 'Microsoft YaHei'; */\n"
                                             "    padding: 5px 12px 6px 12px;\n"
                                             "    outline: none;\n"
                                             "}\n"
                                             "\n"
                                             "ToolButton {\n"
                                             "    padding: 5px 9px 6px 8px;\n"
                                             "}\n"
                                             "\n"
                                             "PushButton[hasIcon=false] {\n"
                                             "    padding: 5px 12px 6px 12px;\n"
                                             "}\n"
                                             "\n"
                                             "PushButton[hasIcon=true] {\n"
                                             "    padding: 5px 12px 6px 36px;\n"
                                             "}\n"
                                             "\n"
                                             "DropDownToolButton, PrimaryDropDownToolButton {\n"
                                             "    padding: 5px 31px 6px 8px;\n"
                                             "}\n"
                                             "\n"
                                             "DropDownPushButton[hasIcon=false],\n"
                                             "PrimaryDropDownPushButton[hasIcon=false] {\n"
                                             "    padding: 5px 31px 6px 12px;\n"
                                             "}\n"
                                             "\n"
                                             "DropDownPushButton[hasIcon=true],\n"
                                             "PrimaryDropDownPushButton[hasIcon=true] {\n"
                                             "    padding: 5px 31px 6px 36px;\n"
                                             "}\n"
                                             "\n"
                                             "PushButton:hover, ToolButton:hover, ToggleButton:hover, To"
                                             "ggleToolButton:hover {\n"
                                             "    background: rgba(249, 249, 249, 0.5);\n"
                                             "}\n"
                                             "\n"
                                             "PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
                                             "    color: rgba(0, 0, 0, 0.63);\n"
                                             "    background: rgba(249, 249, 249, 0.3);\n"
                                             "    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
                                             "}\n"
                                             "\n"
                                             "PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
                                             "    color: rgba(0, 0, 0, 0.36);\n"
                                             "    background: rgba(249, 249, 249, 0.3);\n"
                                             "    border: 1px solid rgba(0, 0, 0, 0.06);\n"
                                             "    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "PrimaryPushButton,\n"
                                             "PrimaryToolButton,\n"
                                             "ToggleButton:checked,\n"
                                             "ToggleToolButton:checked {\n"
                                             "    color: white;\n"
                                             "    background-color: #009faa;\n"
                                             "    border: 1px solid #00a7b3;\n"
                                             "    border-bottom: 1px solid #007780;\n"
                                             "}\n"
                                             "\n"
                                             "PrimaryPushButton:hover,\n"
                                             "PrimaryToolButton:hover,\n"
                                             "ToggleButton:checked:hover,\n"
                                             "ToggleToolButton:checked:hover {\n"
                                             "    background-color: #00a7b3"
                                             ";\n"
                                             "    border: 1px solid #2daab3;\n"
                                             "    border-bottom: 1px solid #007780;\n"
                                             "}\n"
                                             "\n"
                                             "PrimaryPushButton:pressed,\n"
                                             "PrimaryToolButton:pressed,\n"
                                             "ToggleButton:checked:pressed,\n"
                                             "ToggleToolButton:checked:pressed {\n"
                                             "    color: rgba(255, 255, 255, 0.63);\n"
                                             "    background-color: #3eabb3;\n"
                                             "    border: 1px solid #3eabb3;\n"
                                             "}\n"
                                             "\n"
                                             "PrimaryPushButton:disabled,\n"
                                             "PrimaryToolButton:disabled,\n"
                                             "ToggleButton:checked:disabled,\n"
                                             "ToggleToolButton:checked:disabled {\n"
                                             "    color: rgba(255, 255, 255, 0.9);\n"
                                             "    background-color: rgb(205, 205, 205);\n"
                                             "    border: 1px solid rgb(205, 205, 205);\n"
                                             "}\n"
                                             "\n"
                                             "SplitDropButton,\n"
                                             "PrimarySplitDropButton {\n"
                                             "    border-left: none;\n"
                                             "    border-top-left-radius: 0;\n"
                                             "    border-bottom-left-radius: 0;\n"
                                             "}\n"
                                             "\n"
                                             "#splitPushButton,\n"
                                             "#splitToolButton,\n"
                                             "#primarySplitPushButton,\n"
                                             "#primarySplitToolButton {\n"
                                             "    border-top-right-radius: 0;\n"
                                             "    border-bottom-right-radius: 0;\n"
                                             "}\n"
                                             "\n"
                                             "#splitPushButton:pressed,\n"
                                             "#splitTool"
                                             "Button:pressed,\n"
                                             "SplitDropButton:pressed {\n"
                                             "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                             "}\n"
                                             "\n"
                                             "PrimarySplitDropButton:pressed {\n"
                                             "    border-bottom: 1px solid #007780;\n"
                                             "}\n"
                                             "\n"
                                             "#primarySplitPushButton, #primarySplitToolButton {\n"
                                             "    border-right: 1px solid #3eabb3;\n"
                                             "}\n"
                                             "\n"
                                             "#primarySplitPushButton:pressed, #primarySplitToolButton:pressed {\n"
                                             "    border-bottom: 1px solid #007780;\n"
                                             "}\n"
                                             "\n"
                                             "HyperlinkButton {\n"
                                             "    /* font: 14px 'Segoe UI', 'Microsoft YaHei'; */\n"
                                             "    padding: 6px 12px 6px 12px;\n"
                                             "    color: #009faa;\n"
                                             "    border: none;\n"
                                             "    border-radius: 6px;\n"
                                             "    background-color: transparent;\n"
                                             "}\n"
                                             "\n"
                                             "HyperlinkButton[hasIcon=false] {\n"
                                             "    padding: 6px 12px 6px 12px;\n"
                                             "}\n"
                                             "\n"
                                             "HyperlinkButton[hasIcon=true] {\n"
                                             "    padding: 6px 12px 6px 36px;\n"
                                             "}\n"
                                             "\n"
                                             "HyperlinkButton:hover {\n"
                                             "    color: #009faa;\n"
                                             "    background-color: rgba(0, 0, 0, 10);\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "\n"
                                             "HyperlinkButton:pressed {\n"
                                             "    color: #009faa;\n"
                                             ""
                                             "    background-color: rgba(0, 0, 0, 6);\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "\n"
                                             "HyperlinkButton:disabled {\n"
                                             "    color: rgba(0, 0, 0, 0.43);\n"
                                             "    background-color: transparent;\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "RadioButton {\n"
                                             "    min-height: 24px;\n"
                                             "    max-height: 24px;\n"
                                             "    background-color: transparent;\n"
                                             "    font: 14px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';\n"
                                             "    color: black;\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator {\n"
                                             "    width: 18px;\n"
                                             "    height: 18px;\n"
                                             "    border-radius: 11px;\n"
                                             "    border: 2px solid #999999;\n"
                                             "    background-color: rgba(0, 0, 0, 5);\n"
                                             "    margin-right: 4px;\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:hover {\n"
                                             "    background-color: rgba(0, 0, 0, 0);\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:pressed {\n"
                                             "    border: 2px solid #bbbbbb;\n"
                                             "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                             "            stop:0 rgb(255, 255, 255),\n"
                                             "            stop:0.5 rgb(255, 255, 255),\n"
                                             "            stop:0.6 rgb(225, 2"
                                             "24, 223),\n"
                                             "            stop:1 rgb(225, 224, 223));\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:checked {\n"
                                             "    height: 22px;\n"
                                             "    width: 22px;\n"
                                             "    border: none;\n"
                                             "    border-radius: 11px;\n"
                                             "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                             "            stop:0 rgb(255, 255, 255),\n"
                                             "            stop:0.5 rgb(255, 255, 255),\n"
                                             "            stop:0.6 #009faa,\n"
                                             "            stop:1 #009faa);\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:checked:hover {\n"
                                             "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                             "            stop:0 rgb(255, 255, 255),\n"
                                             "            stop:0.6 rgb(255, 255, 255),\n"
                                             "            stop:0.7 #009faa,\n"
                                             "            stop:1 #009faa);\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:checked:pressed {\n"
                                             "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                             "            stop:0 rgb(255, 255, 255),\n"
                                             "            stop:0.5 rgb(255, 255, 255),\n"
                                             "            stop:0.6 #0"
                                             "09faa,\n"
                                             "            stop:1 #009faa);\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton:disabled {\n"
                                             "    color: rgba(0, 0, 0, 110);\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:disabled {\n"
                                             "    border: 2px solid #bbbbbb;\n"
                                             "    background-color: transparent;\n"
                                             "}\n"
                                             "\n"
                                             "RadioButton::indicator:disabled:checked {\n"
                                             "    border: none;\n"
                                             "    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,\n"
                                             "            stop:0 rgb(255, 255, 255),\n"
                                             "            stop:0.5 rgb(255, 255, 255),\n"
                                             "            stop:0.6 rgba(0, 0, 0, 0.2169),\n"
                                             "            stop:1 rgba(0, 0, 0, 0.2169));\n"
                                             "}\n"
                                             "\n"
                                             "TransparentToolButton,\n"
                                             "TransparentToggleToolButton,\n"
                                             "TransparentDropDownToolButton,\n"
                                             "TransparentPushButton,\n"
                                             "TransparentDropDownPushButton,\n"
                                             "TransparentTogglePushButton {\n"
                                             "    background-color: transparent;\n"
                                             "    border: none;\n"
                                             "    border-radius: 5px;\n"
                                             "    margin: 0;\n"
                                             "}\n"
                                             "\n"
                                             "TransparentToolButton:hover,\n"
                                             "TransparentToggleToolButton:hover,\n"
                                             "TransparentDropDownToolButton:ho"
                                             "ver,\n"
                                             "TransparentPushButton:hover,\n"
                                             "TransparentDropDownPushButton:hover,\n"
                                             "TransparentTogglePushButton:hover {\n"
                                             "    background-color: rgba(0, 0, 0, 9);\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "\n"
                                             "TransparentToolButton:pressed,\n"
                                             "TransparentToggleToolButton:pressed,\n"
                                             "TransparentDropDownToolButton:pressed,\n"
                                             "TransparentPushButton:pressed,\n"
                                             "TransparentDropDownPushButton:pressed,\n"
                                             "TransparentTogglePushButton:pressed {\n"
                                             "    background-color: rgba(0, 0, 0, 6);\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "\n"
                                             "TransparentToolButton:disabled,\n"
                                             "TransparentToggleToolButton:disabled,\n"
                                             "TransparentDropDownToolButton:disabled,\n"
                                             "TransprentPushButton:disabled,\n"
                                             "TransparentDropDownPushButton:disabled,\n"
                                             "TransprentTogglePushButton:disabled {\n"
                                             "    background-color: transparent;\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "PillPushButton,\n"
                                             "PillPushButton:hover,\n"
                                             "PillPushButton:pressed,\n"
                                             "PillPushButton:disabled,\n"
                                             "PillPushButton:checked,\n"
                                             "PillPushButton:checked:hover,\n"
                                             "PillPushButton:checked:p"
                                             "ressed,\n"
                                             "PillPushButton:disabled:checked,\n"
                                             "PillToolButton,\n"
                                             "PillToolButton:hover,\n"
                                             "PillToolButton:pressed,\n"
                                             "PillToolButton:disabled,\n"
                                             "PillToolButton:checked,\n"
                                             "PillToolButton:checked:hover,\n"
                                             "PillToolButton:checked:pressed,\n"
                                             "PillToolButton:disabled:checked {\n"
                                             "    background-color: transparent;\n"
                                             "    border: none;\n"
                                             "}\n"
                                             "")
        icon = QIcon()
        icon.addFile(u"../file/background/9165747_send_mail_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.PushButton_choose.setIcon(icon)

        self.horizontalLayout.addWidget(self.PushButton_choose)

        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)

        self.verticalLayout.addLayout(self.horizontalLayout)
